[2023-11-06T12:06:03.353+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-18T00:00:00+00:00 [queued]>
[2023-11-06T12:06:03.373+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-18T00:00:00+00:00 [queued]>
[2023-11-06T12:06:03.374+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-06T12:06:03.407+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task_a> on 2023-10-18 00:00:00+00:00
[2023-11-06T12:06:03.413+0000] {standard_task_runner.py:57} INFO - Started process 844 to run task
[2023-11-06T12:06:03.420+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'catchup_and_backfill_dag', 'task_a', 'scheduled__2023-10-18T00:00:00+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/catchup_and_backfill_dag.py', '--cfg-path', '/tmp/tmp2rtmpoib']
[2023-11-06T12:06:03.426+0000] {standard_task_runner.py:85} INFO - Job 92: Subtask task_a
[2023-11-06T12:06:03.536+0000] {task_command.py:416} INFO - Running <TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-18T00:00:00+00:00 [running]> on host cf1baac588aa
[2023-11-06T12:06:03.727+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='safarnejad' AIRFLOW_CTX_DAG_ID='catchup_and_backfill_dag' AIRFLOW_CTX_TASK_ID='task_a' AIRFLOW_CTX_EXECUTION_DATE='2023-10-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-18T00:00:00+00:00'
[2023-11-06T12:06:03.730+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-06T12:06:03.734+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo Hello World :)']
[2023-11-06T12:06:03.750+0000] {subprocess.py:86} INFO - Output:
[2023-11-06T12:06:03.754+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: syntax error near unexpected token `)'
[2023-11-06T12:06:03.755+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: `echo Hello World :)'
[2023-11-06T12:06:03.756+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-06T12:06:03.778+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-06T12:06:03.788+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=catchup_and_backfill_dag, task_id=task_a, execution_date=20231018T000000, start_date=20231106T120603, end_date=20231106T120603
[2023-11-06T12:06:03.818+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 92 for task task_a (Bash command failed. The command returned a non-zero exit code 2.; 844)
[2023-11-06T12:06:03.843+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-06T12:06:03.886+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-06T12:19:06.362+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-18T00:00:00+00:00 [queued]>
[2023-11-06T12:19:06.384+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-18T00:00:00+00:00 [queued]>
[2023-11-06T12:19:06.386+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-06T12:19:06.441+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task_a> on 2023-10-18 00:00:00+00:00
[2023-11-06T12:19:06.456+0000] {standard_task_runner.py:57} INFO - Started process 2043 to run task
[2023-11-06T12:19:06.463+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'catchup_and_backfill_dag', 'task_a', 'scheduled__2023-10-18T00:00:00+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/catchup_and_backfill_dag.py', '--cfg-path', '/tmp/tmpmowx3a76']
[2023-11-06T12:19:06.470+0000] {standard_task_runner.py:85} INFO - Job 164: Subtask task_a
[2023-11-06T12:19:06.597+0000] {task_command.py:416} INFO - Running <TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-18T00:00:00+00:00 [running]> on host cf1baac588aa
[2023-11-06T12:19:06.823+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='safarnejad' AIRFLOW_CTX_DAG_ID='catchup_and_backfill_dag' AIRFLOW_CTX_TASK_ID='task_a' AIRFLOW_CTX_EXECUTION_DATE='2023-10-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-18T00:00:00+00:00'
[2023-11-06T12:19:06.829+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-06T12:19:06.831+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo Hello World.']
[2023-11-06T12:19:06.905+0000] {subprocess.py:86} INFO - Output:
[2023-11-06T12:19:06.909+0000] {subprocess.py:93} INFO - Hello World.
[2023-11-06T12:19:06.911+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-06T12:19:06.991+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=catchup_and_backfill_dag, task_id=task_a, execution_date=20231018T000000, start_date=20231106T121906, end_date=20231106T121906
[2023-11-06T12:19:07.044+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-06T12:19:07.091+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
