[2023-11-06T12:06:03.493+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-19T00:00:00+00:00 [queued]>
[2023-11-06T12:06:03.515+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-19T00:00:00+00:00 [queued]>
[2023-11-06T12:06:03.516+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-06T12:06:03.574+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task_a> on 2023-10-19 00:00:00+00:00
[2023-11-06T12:06:03.583+0000] {standard_task_runner.py:57} INFO - Started process 847 to run task
[2023-11-06T12:06:03.590+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'catchup_and_backfill_dag', 'task_a', 'scheduled__2023-10-19T00:00:00+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/catchup_and_backfill_dag.py', '--cfg-path', '/tmp/tmpn_p2f6xj']
[2023-11-06T12:06:03.596+0000] {standard_task_runner.py:85} INFO - Job 93: Subtask task_a
[2023-11-06T12:06:03.717+0000] {task_command.py:416} INFO - Running <TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-19T00:00:00+00:00 [running]> on host cf1baac588aa
[2023-11-06T12:06:03.917+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='safarnejad' AIRFLOW_CTX_DAG_ID='catchup_and_backfill_dag' AIRFLOW_CTX_TASK_ID='task_a' AIRFLOW_CTX_EXECUTION_DATE='2023-10-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-19T00:00:00+00:00'
[2023-11-06T12:06:03.920+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-06T12:06:03.924+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo Hello World :)']
[2023-11-06T12:06:03.953+0000] {subprocess.py:86} INFO - Output:
[2023-11-06T12:06:03.959+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: syntax error near unexpected token `)'
[2023-11-06T12:06:03.960+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: `echo Hello World :)'
[2023-11-06T12:06:03.961+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-06T12:06:03.984+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-06T12:06:03.993+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=catchup_and_backfill_dag, task_id=task_a, execution_date=20231019T000000, start_date=20231106T120603, end_date=20231106T120603
[2023-11-06T12:06:04.031+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 93 for task task_a (Bash command failed. The command returned a non-zero exit code 2.; 847)
[2023-11-06T12:06:04.054+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-06T12:06:04.097+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-06T12:19:06.556+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-19T00:00:00+00:00 [queued]>
[2023-11-06T12:19:06.579+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-19T00:00:00+00:00 [queued]>
[2023-11-06T12:19:06.580+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-06T12:19:06.637+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task_a> on 2023-10-19 00:00:00+00:00
[2023-11-06T12:19:06.656+0000] {standard_task_runner.py:57} INFO - Started process 2047 to run task
[2023-11-06T12:19:06.679+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'catchup_and_backfill_dag', 'task_a', 'scheduled__2023-10-19T00:00:00+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/catchup_and_backfill_dag.py', '--cfg-path', '/tmp/tmpxdb22hbz']
[2023-11-06T12:19:06.691+0000] {standard_task_runner.py:85} INFO - Job 165: Subtask task_a
[2023-11-06T12:19:06.830+0000] {task_command.py:416} INFO - Running <TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-19T00:00:00+00:00 [running]> on host cf1baac588aa
[2023-11-06T12:19:07.163+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='safarnejad' AIRFLOW_CTX_DAG_ID='catchup_and_backfill_dag' AIRFLOW_CTX_TASK_ID='task_a' AIRFLOW_CTX_EXECUTION_DATE='2023-10-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-19T00:00:00+00:00'
[2023-11-06T12:19:07.173+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-06T12:19:07.178+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo Hello World.']
[2023-11-06T12:19:07.196+0000] {subprocess.py:86} INFO - Output:
[2023-11-06T12:19:07.199+0000] {subprocess.py:93} INFO - Hello World.
[2023-11-06T12:19:07.200+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-06T12:19:07.252+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=catchup_and_backfill_dag, task_id=task_a, execution_date=20231019T000000, start_date=20231106T121906, end_date=20231106T121907
[2023-11-06T12:19:07.291+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-06T12:19:07.332+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
